{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 99,
   "id": "a4d89599",
   "metadata": {},
   "outputs": [],
   "source": [
    "from dash import Dash, html, dcc\n",
    "import plotly.express as px\n",
    "import pandas as pd\n",
    "from dash.dependencies import Input, Output, State\n",
    "import dash_bootstrap_components as dbc\n",
    "import numpy as np\n",
    "import pickle\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 100,
   "id": "80786b62",
   "metadata": {},
   "outputs": [],
   "source": [
    "app = Dash(__name__)\n",
    "app.title = 'Machine Learning Model Deployment'\n",
    "server = app.server"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 101,
   "id": "752db54e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# load model\n",
    "with open('pkl/batting_basic_model.pkl', 'rb') as f:\n",
    "    model = pickle.load(f)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 102,
   "id": "ba1c1ba2",
   "metadata": {},
   "outputs": [],
   "source": [
    "# App Layout \n",
    "app.layout = html.Div([\n",
    "    dbc.Row([html.H3(children='Predict Batter Salary')]),\n",
    "        dbc.Row([\n",
    "        dbc.Col(html.Label(children='Salary Difference:'), width={\"order\": \"first\"}),\n",
    "        dbc.Col(dcc.Slider(min=0, max=10000000, value = 2000000, id='Salary_Difference')) \n",
    "    ]),\n",
    "    dbc.Row([\n",
    "        dbc.Col(html.Label(children='Age:'), width={\"order\": \"first\"}),\n",
    "        dbc.Col(dcc.Slider(min=20, max=40, value = 28, id='Age')) \n",
    "    ]),\n",
    "    dbc.Row([\n",
    "        dbc.Col(html.Label(children='Hits:'), width={\"order\": \"first\"}),\n",
    "        dbc.Col(dcc.Slider(min=0, max=250,  value = 100, id='H')) \n",
    "    ]),\n",
    "    dbc.Row([\n",
    "        dbc.Col(html.Label(children='Runs:'), width={\"order\": \"first\"}),\n",
    "        dbc.Col(dcc.Slider(min=0, max=250,  value = 50, id='R')) \n",
    "    ]),\n",
    "    dbc.Row([\n",
    "        dbc.Col(html.Label(children='RBIs:'), width={\"order\": \"first\"}),\n",
    "       dbc.Col( dcc.Slider(min=0, max=150,  value = 50, id='RBI')) \n",
    "    ]),   \n",
    "    dbc.Row([\n",
    "        dbc.Col(html.Label(children='Walks:'), width={\"order\": \"first\"}),\n",
    "       dbc.Col( dcc.Slider(min=0, max=150,  value = 50, id='BB')) \n",
    "    ]), \n",
    "    dbc.Row([\n",
    "        dbc.Col(html.Label(children='Srikeouts:'), width={\"order\": \"first\"}),\n",
    "       dbc.Col( dcc.Slider(min=0, max=250,  value = 50, id='SO')) \n",
    "    ]), \n",
    "    dbc.Row([\n",
    "        dbc.Col(html.Label(children='Sac Flys:'), width={\"order\": \"first\"}),\n",
    "       dbc.Col( dcc.Slider(min=0, max=20,  value = 3, id='SF')) \n",
    "    ]), \n",
    "    dbc.Row([\n",
    "        dbc.Col(html.Label(children='Sac Hits:'), width={\"order\": \"first\"}),\n",
    "       dbc.Col( dcc.Slider(min=0, max=20,  value = 3, id='SH')) \n",
    "    ]), \n",
    "    dbc.Row([\n",
    "        dbc.Col(html.Label(children='Double Plays:'), width={\"order\": \"first\"}),\n",
    "       dbc.Col( dcc.Slider(min=0, max=20,  value = 5, id='GDP')) \n",
    "    ]), \n",
    "    dbc.Row([\n",
    "        dbc.Col(html.Label(children='Stolen Bases:'), width={\"order\": \"first\"}),\n",
    "       dbc.Col( dcc.Slider(min=0, max=100,  value = 10, id='SB')) \n",
    "    ]), \n",
    "    dbc.Row([\n",
    "        dbc.Col(html.Label(children='OPS:'), width={\"order\": \"first\"}),\n",
    "       dbc.Col( dcc.Slider(min=0, max=1.5,  value = 1.2, id='OPS')) \n",
    "    ]), \n",
    "    dbc.Row([dbc.Button('Submit', id='submit-val', n_clicks=0, color=\"primary\")]),\n",
    "    html.Br(),\n",
    "    dbc.Row([html.Div(id='prediction output')])\n",
    "    \n",
    "    ], style = {'padding': '0px 0px 0px 150px', 'width': '50%'})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 103,
   "id": "909b975e",
   "metadata": {},
   "outputs": [],
   "source": [
    "### Callback to produce the prediction ######################### \n",
    "@app.callback(\n",
    "    Output('prediction output', 'children'),\n",
    "    Input('submit-val', 'n_clicks'),\n",
    "    State('Salary Difference', 'value'),\n",
    "    State('Age', 'value'),\n",
    "    State('H', 'value'), \n",
    "    State('R', 'value'),\n",
    "    State('RBI', 'value'),\n",
    "    State('BB', 'value'), \n",
    "    State('SO', 'value'),\n",
    "    State('SF', 'value'),\n",
    "    State('SH', 'value'), \n",
    "    State('GDP', 'value'),\n",
    "    State('SB', 'value'),\n",
    "    State('OPS', 'value')\n",
    ")\n",
    "   \n",
    "def update_output(n_clicks, Salary_Difference, Age, H, R, RBI, BB, SO, SF, SH, GDP, SB, OPS):    \n",
    "    x = np.array([[float(Salary_Difference), \n",
    "                   float(Age), \n",
    "                   float(H), \n",
    "                   float(R),\n",
    "                   float(RBI), \n",
    "                   float(BB),\n",
    "                   float(SO), \n",
    "                   float(SF),\n",
    "                   float(SH), \n",
    "                   float(GDP),\n",
    "                   float(SB),\n",
    "                   float(OPS)\n",
    "                  ]])\n",
    "    \n",
    "    prediction =  model.predict(x)[0]\n",
    "    return f'The predicted batter salary is {output}.'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f5e1e838",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash is running on http://127.0.0.1:8055/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8055/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8055/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8055/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8055/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8055/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8055/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8055/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8055/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8055/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8055/\n",
      "\n",
      " * Serving Flask app '__main__'\n",
      " * Debug mode: off\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/flask/app.py\", line 1812, in full_dispatch_request\n",
      "    self.ensure_sync(func)()\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 1290, in _setup_server\n",
      "    ) = inputs_to_dict(inputs)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 795, in _generate_scripts_html\n",
      "    package_name,\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 741, in _collect_and_register_resources\n",
      "    self._inline_scripts.extend(_callback.GLOBAL_INLINE_SCRIPTS)\n",
      "  File \"/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/dash.py\", line 720, in _relative_url_path\n",
      "    self._collect_and_register_resources(\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/miniforge3/envs/tf_miniforge/lib/python3.10/site-packages/dash/deps/prop-types@15.8.1.min.js'\n"
     ]
    }
   ],
   "source": [
    "### Run the App ###############################################\n",
    "if __name__ == '__main__':\n",
    "    app.run_server(port=8055,\n",
    "                   debug=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b6c48bbb",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4175cec8",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dd8d110c",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6eefd13b",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f98ad2ef",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ba8faf71",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "28f0b765",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9348b207",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b896cd32",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "247e5c4a",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f1288518",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
